#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2016, Joyent, Inc.
#

#
# Rsync metric-agent
#

set -o errexit

TOP=$(cd $(dirname $0)/../; pwd)
NODE=root@$1
METRIC_AGENT_DIR=/opt/smartdc/agents/lib/node_modules/metric-agent

extraOpts=
if [[ $(uname -s) != "SunOS" ]]; then
    extraOpts="--exclude *.node --exclude build"
fi

rsync -av ${TOP}/ \
    $NODE:${METRIC_AGENT_DIR} \
    $extraOpts \
    --exclude .git/ \
    --exclude /deps/ \
    --exclude /docs/ \
    --exclude /tools/ \
    --exclude /tmp/

state=$(ssh ${NODE} svcs -H -o state metric-agent)
if [[ "$state" == "maintenance" ]]; then
    ssh ${NODE} svcadm clear metric-agent
else
    ssh ${NODE} svcadm restart metric-agent
fi
